#
# Basic application settings
#
application_settings:

  # List of headers params to be skipped
  skipped_headers:
    - accept
    - authority
    - user-agent
    - content-type
    - origin
    - sec-fetch-site
    - sec-fetch-mode
    - sec-fetch-dest
    - referer
